language: java

branches:
  except:
    - gh-pages

before_install:
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=~/builds/lexs/webimageloader/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter platform-tools,android-16 --no-ui --force --no-https
